### ISSUE TITLE
Check if script output location exists and create it if not

### ISSUE THREAD

**Issue by Dav-id-V** [jeffpriz/get-postman-scripts#4]
If the script output location does not exists an error is thrown that collections.json file could not be found. It would be better to check if the script output location exists en create it if not, as is done with the environments folder.

**Comment by jeffpriz** [comment]
That's a good case.  I'm on it.

**Comment by jeffpriz** [comment]
@Dav-id-V I just published v 1.0.1 that should address this.. when your server updates to this version I think you should be good

**Comment by Dav-id-V** [comment]
Just tested it and it is fixed :-). Thanks
