### ISSUE TITLE
Collection Filtering

### ISSUE THREAD

**Issue by PeterAnaniaHC** [jeffpriz/get-postman-scripts#7]
This isn't your issue, per se. What's happening is... Because our team has so many collections, no matter whose api key we use the tool downloads all of them. We're using the tool in a Azure CICD pipeline using YAML. What happens then is, as it gets to the end of our list it issues a warning telling us that it cannot fetch the next collection because the rate limit has exceeded. This is a Postman thing, so like I said it's nothing you've done, but if there was a way to filter what the tool fetches (by collection name say) then that would be great. 

Because even if we upgraded to an account without that bandwidth consideration, we'd still be downloading collections for other projects into the artifacts directory of this project. See?

**Comment by jeffpriz** [comment]
The task does have a pause duration built in.. this allows you to pause so that your rate limit isn't exceeded...
